chore: Arduino CLIやMbed CLIをインストールする #204 (#239)
* chore: Arduino CLIやMbed CLIをインストールする #204

* chore: CSellの辞書を更新した #204

* chore: Arduino CLIやMbed CLIをインストール #204

* chore: Arduino CLIやMbed CLIでのビルドテストを追加 #204

* fix: mbedコマンドではなくmbed-cliコマンドを利用する #204

* fix: devcontainer exec を利用する #204

* chore: Dev Container CLIのバージョンを0.50.0に固定する #204

0.50.1ではエラーが発生したため、その前のバージョンに固定する

* feat: Mbed CLI 1でのビルドをtmpディレクトリ中で行う #204

* feat: devcontainers/ci を利用したワークフローに変更 #204

* fix: CIの git の safe.directory の設定時のエラーを修正 #204

* chore: テスト中のコマンドの終了ステータスが0以外のときに中断する #204

* fix: コンパイルエラーを修正 #204

* fix: 用意したソースコードでビルドテストするように変更 #204

* chore: multiplatform build #204

* Revert "chore: multiplatform build #204"

This reverts commit 4875af0a391194555b06e7c233cb6e9b81008165.

* chore: ビルド成功時にイメージをpushする #204

* chore: Arduino CLIでのビルド中にログを出力する #204

* fix: `No space left on device`対策を実施 #204

* chore: 削除する容量を増やした #204

diff --git a/.github/workflows/devcontainer.yml b/.github/workflows/devcontainer.yml
--- a/.github/workflows/devcontainer.yml
+++ b/.github/workflows/devcontainer.yml
@@ -4,9 +4,13 @@ on:
   push:
     branches:
       - main
+    paths:
+      - ".devcontainer/**"
   pull_request:
     branches:
       - "main"
+    paths:
+      - ".devcontainer/**"
   workflow_dispatch:
 
 jobs:
@@ -16,16 +20,46 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2
         with:
-          node-version: 18.x
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install Dev Container CLI
-        run: npm install -g @devcontainers/cli
+      - name: Build and run dev container task
+        uses: devcontainers/ci@v0.3
+        with:
+          imageName: ghcr.io/${{ github.repository }}
+          cacheFrom: ghcr.io/${{ github.repository }}
+          push: filter
+          refFilterForPush: refs/heads/main
+          runCmd: |
+            # In runCmd, processing continues except for the last command, even if the exit status is not 0.
+            set -e
 
-      - name: Building image
-        run: devcontainer build --workspace-folder .
+            # Arduino CLI
+            arduino-cli compile --fqbn esp32:esp32:esp32 --library . --verbose .github/workflows/build-arduino-cli
+            arduino-cli compile --fqbn STMicroelectronics:stm32:GenF3 --library . --verbose .github/workflows/build-arduino-cli
+            arduino-cli compile --fqbn arduino:mbed:pico --library . --verbose .github/workflows/build-arduino-cli
 
-      - name: Spins up containers
-        run: devcontainer up --workspace-folder .
+            # Mbed CLI 1
+            mkdir /tmp/mbed-cli-1
+            cd /tmp/mbed-cli-1
+            mbed new .
+            mbed deploy
+            ln -s /workspaces/spirit
+            cp /workspaces/spirit/.github/workflows/build-mbed/main.cpp .
+            mbed compile -t GCC_ARM -m NUCLEO_F303K8 --profile release
+            # Remove build directory to save disk space
+            rm -rf /tmp/mbed-cli-1
+
+            # Mbed CLI 2
+            mkdir /tmp/mbed-cli-2
+            cd /tmp/mbed-cli-2
+            mbed-tools new .
+            mbed-tools deploy
+            ln -s /workspaces/spirit
+            cp /workspaces/spirit/.github/workflows/build-mbed/main.cpp .
+            cp /workspaces/spirit/.github/workflows/build-mbed-tools/CMakeLists.txt .
+            mbed-tools compile -t GCC_ARM -m NUCLEO_F303K8 --profile release
